CREATE TABLE IF NOT EXISTS todos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_todos_created_at
    ON todos (created_at DESC);

CREATE TABLE IF NOT EXISTS bom_parts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id INTEGER REFERENCES bom_parts (id) ON DELETE CASCADE,
    sku VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    part_type VARCHAR(30) NOT NULL,
    quantity NUMERIC(12, 3) NOT NULL DEFAULT 1,
    unit VARCHAR(20) NOT NULL DEFAULT 'ea',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_bom_parts_no_self_parent CHECK (id IS NULL OR id <> parent_id),
    CONSTRAINT ck_bom_parts_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS ix_bom_parts_parent_id
    ON bom_parts (parent_id);

CREATE INDEX IF NOT EXISTS ix_bom_parts_part_type
    ON bom_parts (part_type);

CREATE TABLE IF NOT EXISTS entities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    code VARCHAR(60) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (entity_type, code)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_entities_id_entity_type
    ON entities (id, entity_type);

CREATE TABLE IF NOT EXISTS entity_attributes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    code VARCHAR(60) NOT NULL,
    label VARCHAR(120) NOT NULL,
    value_type VARCHAR(20) NOT NULL,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    UNIQUE (entity_type, code),
    CONSTRAINT ck_entity_attributes_value_type
        CHECK (value_type IN ('text', 'number', 'boolean', 'date'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_entity_attributes_id_entity_type
    ON entity_attributes (id, entity_type);

CREATE TABLE IF NOT EXISTS entity_attribute_values (
    entity_id INTEGER NOT NULL REFERENCES entities (id) ON DELETE CASCADE,
    attribute_id INTEGER NOT NULL REFERENCES entity_attributes (id) ON DELETE CASCADE,
    entity_type VARCHAR(50) NOT NULL,
    value_text TEXT,
    value_number NUMERIC(18, 4),
    value_boolean BOOLEAN,
    value_date DATE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (entity_id, attribute_id),
    CONSTRAINT ck_entity_attribute_values_single_value
        CHECK (
            num_nonnulls(value_text, value_number, value_boolean, value_date) = 1
        ),
    CONSTRAINT fk_entity_attribute_values_entity_type
        FOREIGN KEY (entity_id, entity_type)
        REFERENCES entities (id, entity_type)
        ON DELETE CASCADE,
    CONSTRAINT fk_entity_attribute_values_attribute_type
        FOREIGN KEY (attribute_id, entity_type)
        REFERENCES entity_attributes (id, entity_type)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_entity_attribute_values_attribute_id
    ON entity_attribute_values (attribute_id);
